server:
  port: 1117

spring:
  application:
    name: Jkeep

  # 指定数据源
  datasource:
    url: jdbc:mysql://139.196.160.176:3306/jkeep?autoReconnect=true&useUnicode=true&amp&characterEncoding=UTF-8
    username: root
    password: ml-mysql
    driver-class-name: com.mysql.cj.jdbc.Driver

  #jap 配置
  jpa:
    # 数据库
    database: mysql
    database-platform: org.hibernate.dialect.MySQL8Dialect
    # 是否控制台打印 sql
    show-sql: true
    hibernate:
      #      validate              加载hibernate时，验证创建数据库表结构
      #      create                每次加载hibernate，重新创建数据库表结构，这就是导致数据库表数据丢失的原因。
      #      create-drop        加载hibernate时创建，退出是删除表结构
      #      update               加载hibernate自动更新数据库结构
      ddl-auto: none
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      use-new-id-generator-mappings: true

  # thymeleaf 配置
  thymeleaf:
    # dev 关闭缓存. OnLine 需改true
    cache: false

# ======= 日志配置 =======
logging:
  # 日志路径
  path: /work/logs
  file: /work/logs/${spring.application.name}.log
  # 日志输出级别
  level:
    root: info
    org:
      springframework: info
      # 打印 sql 参数.
      hibernate:
        type:
          descriptor:
            sql:
              BasicBinder: trace
      ml: debug

# ======= JKeep配置 =======
jkeep:
  # 线程池配置
  threadPool:
    corePoolSize: 200
    maxPoolSize: 1000
    queueCapacity: 1000000
    keepAliveSeconds: 300

  # 日志拦截
  log-aop:
    enable: true

  # 安全认证
  auth:
    token-validity: 7200

  # ali oss
  oss:
    accessKeyId: LTAI4FfJAv7wLdint5kdU48M
    accessKeySecret: mOAULf9oYBGq838wwWjCmUHf8cNnLX
    roleArn: acs:ram::1887307779349821:role/jkeep
    roleSessionName: JKeep-Ram
    endpoint: oss-cn-shanghai.aliyuncs.com
    bucket: jkeep
    catalog: upload/