server:
  port: 1117

spring:
  application:
    name: Jkeep

  # 指定数据源
  datasource:
    url: jdbc:mysql://rm-uf6ei0ncf08876co9zo.mysql.rds.aliyuncs.com:3306/jkeep?autoReconnect=true&useUnicode=true&amp&characterEncoding=UTF-8
    username: jkeep
    password: jkeep2019___
    driver-class-name: com.mysql.cj.jdbc.Driver

  #jap 配置
  jpa:
    # 数据库
    database: mysql
    database-platform: org.hibernate.dialect.MySQL5Dialect
    # 是否控制台打印 sql
    show-sql: true
    hibernate:
      #      validate              加载hibernate时，验证创建数据库表结构
      #      create                每次加载hibernate，重新创建数据库表结构，这就是导致数据库表数据丢失的原因。
      #      create-drop        加载hibernate时创建，退出是删除表结构
      #      update               加载hibernate自动更新数据库结构
      ddl-auto: none
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      use-new-id-generator-mappings: true

#  # redis 配置
#  redis:
#    # 数据库索引 (default:0)
#    database: 0
#    # 服务器地址 (default:localhost)
#    host: 127.0.0.1
#    # 服务器连接端口 (default:6379)
#    port: 32768
#    # 服务器连接密码 (default:空)
#    password:
#    jedis:
#      pool:
#        # 连接池最大连接数 (default:8 , 使用负值表示没有限制)
#        max-active: 8
#        # 连接池最大阻塞等待时间 (default: -1 , 使用负值表示没有限制)
#        max-wait: -1
#        # 连接池中的最大空闲连接 (default:8)
#        max-idle: 8
#        # 连接池中的最小空闲连接 (default:0)
#        min-idle: 0
#    # 连接超时时间 (毫秒)
#    timeout: 500

  # thymeleaf 配置
  thymeleaf:
    # dev 关闭缓存. OnLine 需改true
    cache: false

# ======= 日志配置 =======
logging:
  # 日志路径
  path: /work/logs
  file: /work/logs/${spring.application.name}.log
  # 日志输出级别
  level:
    root: info
    org:
      springframework: info
    com:
      ml: debug

# ======= JKeep配置 =======
JKeep:
  logAop:
    enable: true
